<a href="https://colab.research.google.com/github/OmkarSolat/Data-Science-at-ExcelR/blob/main/Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Sentiment Analysis : Naive Bayes**

In [1]:
#Importing libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
#Reading data
data = pd.read_csv("Hamspam.csv",encoding = "ISO-8859-1")

In [3]:
data.head()

type                                               text
0   ham  Hope you are having a good week. Just checking in
1   ham                            K..give back my thanks.
2   ham        Am also doing in cbe only. But have to pay.
3  spam  complimentary 4 STAR Ibiza Holiday or å£10,000...
4  spam  okmail: Dear Dave this is your final notice to...

In [4]:
data.isnull().sum()

type    0
text    0
dtype: int64

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5559 entries, 0 to 5558
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   type    5559 non-null   object
 1   text    5559 non-null   object
dtypes: object(2)
memory usage: 87.0+ KB


In [6]:
data["type"]=data["type"].map({'ham':0,'spam':1})
#ham-'0' & spam-'1'
# OR -> label encoding can be used

In [7]:
data

type                                               text
0        0  Hope you are having a good week. Just checking in
1        0                            K..give back my thanks.
2        0        Am also doing in cbe only. But have to pay.
3        1  complimentary 4 STAR Ibiza Holiday or å£10,000...
4        1  okmail: Dear Dave this is your final notice to...
...    ...                                                ...
5554     0  You are a great role model. You are giving so ...
5555     0  Awesome, I remember the last time we got someb...
5556     1  If you don't, your prize will go to another cu...
5557     1  SMS. ac JSco: Energy is high, but u may not kn...
5558     0                    Shall call now dear having food

[5559 rows x 2 columns]

In [8]:
#splitting data
#independent and dependent
x= data["text"]
y=data["type"]

In [9]:
#chossing model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [10]:
x = cv.fit_transform(x)

In [11]:
x

<5559x8698 sparse matrix of type '<class 'numpy.int64'>'
	with 73387 stored elements in Compressed Sparse Row format>

In [12]:
x.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [13]:
print(x)

  (0, 3920)	1
  (0, 8628)	1
  (0, 1192)	1
  (0, 3777)	1
  (0, 3575)	1
  (0, 8332)	1
  (0, 4352)	1
  (0, 1982)	1
  (0, 4091)	1
  (1, 3530)	1
  (1, 1358)	1
  (1, 5228)	1
  (1, 7625)	1
  (2, 4091)	1
  (2, 1064)	1
  (2, 1055)	1
  (2, 2699)	1
  (2, 1912)	1
  (2, 5545)	1
  (2, 1785)	1
  (2, 3771)	1
  (2, 7768)	1
  (2, 5742)	1
  (3, 7768)	1
  (3, 2184)	1
  :	:
  (5557, 8067)	1
  (5557, 4447)	1
  (5557, 8384)	1
  (5557, 7015)	1
  (5557, 4934)	1
  (5557, 6414)	2
  (5557, 2920)	1
  (5557, 2911)	2
  (5557, 6204)	1
  (5557, 3852)	1
  (5557, 1117)	1
  (5557, 882)	1
  (5557, 7315)	1
  (5557, 442)	1
  (5557, 4333)	2
  (5557, 441)	1
  (5557, 4551)	1
  (5557, 6949)	1
  (5557, 6152)	1
  (5558, 3777)	1
  (5558, 5427)	1
  (5558, 2472)	1
  (5558, 1817)	1
  (5558, 3296)	1
  (5558, 6799)	1


In [14]:
#model building
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.3,random_state=22)

In [15]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()

In [16]:
#training/fitting
clf.fit(xtrain,ytrain)

MultinomialNB()

In [17]:
#testing/predictions
ypred = clf.predict(xtest)

In [18]:
ypred

array([0, 1, 1, ..., 0, 1, 0])

In [19]:
#Performance metrics
from sklearn.metrics import accuracy_score
print(accuracy_score(ytest,ypred))

0.9766187050359713


In [20]:
clf.predict_proba(xtest)

array([[9.79320740e-01, 2.06792599e-02],
       [5.09654740e-15, 1.00000000e+00],
       [8.60875111e-13, 1.00000000e+00],
       ...,
       [9.99999745e-01, 2.54873704e-07],
       [7.37022093e-02, 9.26297791e-01],
       [9.99950421e-01, 4.95785885e-05]])