<a href="https://colab.research.google.com/github/OmkarSolat/Data-Science-at-ExcelR/blob/main/Numpy_Library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Library

In [ ]:
import numpy as np

In [ ]:
#1D array
arr1 = np.array([1,2,5,3,6,6,7])
arr1

array([1, 2, 5, 3, 6, 6, 7])

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
arr1.shape

(7,)

In [ ]:
#2D array
arr2 = np.array([[1,2,5,4,7,8], [8,7,6,4,9,2]])
arr2

array([[1, 2, 5, 4, 7, 8],
       [8, 7, 6, 4, 9, 2]])

In [ ]:
arr2.shape             # 2 rows & 6 columns

(2, 6)

In [ ]:
#3D array
arr3 = np.array([[[1,2,5,4,7,8], [8,7,6,4,9,2]],
                 [[1,2,5,4,7,8], [8,7,6,4,9,2]],
                 [[1,2,5,4,7,8], [8,7,6,4,9,2]],
                 [[1,2,5,4,7,8], [8,7,6,4,9,2]]])
arr3

array([[[1, 2, 5, 4, 7, 8],
        [8, 7, 6, 4, 9, 2]],

       [[1, 2, 5, 4, 7, 8],
        [8, 7, 6, 4, 9, 2]],

       [[1, 2, 5, 4, 7, 8],
        [8, 7, 6, 4, 9, 2]],

       [[1, 2, 5, 4, 7, 8],
        [8, 7, 6, 4, 9, 2]]])

In [ ]:
arr3.shape
# 4 times 2D array with 2 rows & 6 columns

(4, 2, 6)

In [ ]:
#4D array
arr4 = np.array([[[[1,2,5,4,7,8], [8,7,6,4,9,2]],
                 [[1,2,5,4,7,8], [8,7,6,4,9,2]],
                 [[1,2,5,4,7,8], [8,7,6,4,9,2]],
                 [[1,2,5,4,7,8], [8,7,6,4,9,2]]],

                 [[[1,2,5,4,7,8], [8,7,6,4,9,2]],
                 [[1,2,5,4,7,8], [8,7,6,4,9,2]],
                 [[1,2,5,4,7,8], [8,7,6,4,9,2]],
                 [[1,2,5,4,7,8], [8,7,6,4,9,2]]],

                 [[[1,2,5,4,7,8], [8,7,6,4,9,2]],
                 [[1,2,5,4,7,8], [8,7,6,4,9,2]],
                 [[1,2,5,4,7,8], [8,7,6,4,9,2]],
                 [[1,2,5,4,7,8], [8,7,6,4,9,2]]]])

arr4

array([[[[1, 2, 5, 4, 7, 8],
         [8, 7, 6, 4, 9, 2]],

        [[1, 2, 5, 4, 7, 8],
         [8, 7, 6, 4, 9, 2]],

        [[1, 2, 5, 4, 7, 8],
         [8, 7, 6, 4, 9, 2]],

        [[1, 2, 5, 4, 7, 8],
         [8, 7, 6, 4, 9, 2]]],


       [[[1, 2, 5, 4, 7, 8],
         [8, 7, 6, 4, 9, 2]],

        [[1, 2, 5, 4, 7, 8],
         [8, 7, 6, 4, 9, 2]],

        [[1, 2, 5, 4, 7, 8],
         [8, 7, 6, 4, 9, 2]],

        [[1, 2, 5, 4, 7, 8],
         [8, 7, 6, 4, 9, 2]]],


       [[[1, 2, 5, 4, 7, 8],
         [8, 7, 6, 4, 9, 2]],

        [[1, 2, 5, 4, 7, 8],
         [8, 7, 6, 4, 9, 2]],

        [[1, 2, 5, 4, 7, 8],
         [8, 7, 6, 4, 9, 2]],

        [[1, 2, 5, 4, 7, 8],
         [8, 7, 6, 4, 9, 2]]]])

In [ ]:
arr4.shape
# 3 times an array structure having 4 arrays that contain 2 rows & 6 columns

(3, 4, 2, 6)

* arange()

In [ ]:
arr5 = np.arange(10)
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr6 = np.arange(5,10)
arr6

array([5, 6, 7, 8, 9])

In [ ]:
arr7 = np.arange(1,10,2)
arr7

array([1, 3, 5, 7, 9])

* reshape()

In [ ]:
arr8 = np.arange(20).reshape(4,5)
arr8

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

* random

In [ ]:
x = np.random.randint(1,10,20)         #(start,end,size)
x

array([3, 2, 2, 3, 4, 6, 3, 5, 1, 4, 3, 9, 8, 1, 8, 7, 1, 5, 8, 7])

In [ ]:
x = np.random.randn(5)
x

array([ 0.10053312, -0.06889035,  1.28628462, -0.47636696, -2.1232864 ])

In [ ]:
x = np.random.random(10)
x

array([0.09153102, 0.8730178 , 0.85224648, 0.06209178, 0.33875165,
       0.79308481, 0.36950823, 0.14907957, 0.79604178, 0.87712068])

In [ ]:
x = np.random.choice(100,10,replace = True)         # (int_range ,size,......)
x

array([76, 62, 36, 75, 49, 37, 95, 43, 62, 36])

* linspace

In [ ]:
x = np.linspace(1,10,5)
x

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
# To check interval
for i in range(len(x)-1):
  print(i)
  print('Difference between index',i,'&',i+1,'is', x[i+1] - x[i])

0
Difference between index 0 & 1 is 2.25
1
Difference between index 1 & 2 is 2.25
2
Difference between index 2 & 3 is 2.25
3
Difference between index 3 & 4 is 2.25


* sum()

In [ ]:
arr = np.random.randint(0,9,20).reshape(5,4)
arr

array([[1, 6, 1, 0],
       [8, 5, 6, 6],
       [6, 0, 4, 4],
       [6, 1, 7, 3],
       [1, 5, 4, 4]])

In [ ]:
#columnwise
arr.sum(axis=0)

array([22, 17, 22, 17])

In [ ]:
#rowwise
arr.sum(axis=1)

array([ 8, 25, 14, 17, 14])

In [ ]:
#max
print(arr.max(axis=0))
print(arr.max(axis=1))

[8 6 7 6]
[6 8 6 7 5]


In [ ]:
#min
print(arr.min(axis=0))
print(arr.min(axis=1))

[1 0 1 0]
[0 5 0 1 1]


In [ ]:
#mean
print(arr.mean(axis=0))
print(arr.mean(axis=1))

[4.4 3.4 4.4 3.4]
[2.   6.25 3.5  4.25 3.5 ]


In [ ]:
#cumulative summation
arr = np.random.randint(0,9,20)
print(arr)
np.cumsum(arr)

[6 6 1 6 6 4 0 3 4 6 1 0 6 7 4 1 8 1 5 8]


array([ 6, 12, 13, 19, 25, 29, 29, 32, 36, 42, 43, 43, 49, 56, 60, 61, 69,
       70, 75, 83])

* square

In [ ]:
arr = np.random.randint(1,9,20).reshape(4,5)
print(arr)
np.square(arr)

[[7 3 7 3 4]
 [7 6 5 5 6]
 [7 6 7 5 6]
 [7 7 1 5 7]]


array([[49,  9, 49,  9, 16],
       [49, 36, 25, 25, 36],
       [49, 36, 49, 25, 36],
       [49, 49,  1, 25, 49]])

* sqrt

In [ ]:
arr = np.random.randint(1,9,20).reshape(4,5)
print(arr)
np.sqrt(arr)

[[3 1 8 5 1]
 [3 1 3 6 3]
 [6 1 1 7 7]
 [2 7 7 6 1]]


array([[1.73205081, 1.        , 2.82842712, 2.23606798, 1.        ],
       [1.73205081, 1.        , 1.73205081, 2.44948974, 1.73205081],
       [2.44948974, 1.        , 1.        , 2.64575131, 2.64575131],
       [1.41421356, 2.64575131, 2.64575131, 2.44948974, 1.        ]])

* stacking of arrays

In [ ]:
arr1 = np.random.randint(1,9,20).reshape(4,5)
arr2 = np.random.randint(1,9,20).reshape(4,5)
print(arr1)
print(arr2)

[[6 2 3 4 6]
 [1 1 4 2 3]
 [3 3 6 3 3]
 [6 4 3 2 2]]
[[6 8 3 4 6]
 [5 4 1 3 8]
 [4 1 3 8 5]
 [6 2 6 3 5]]


In [ ]:
#Horizontal stack
#No.of rows should be equal
np.hstack((arr1,arr2))

array([[6, 2, 3, 4, 6, 6, 8, 3, 4, 6],
       [1, 1, 4, 2, 3, 5, 4, 1, 3, 8],
       [3, 3, 6, 3, 3, 4, 1, 3, 8, 5],
       [6, 4, 3, 2, 2, 6, 2, 6, 3, 5]])

In [ ]:
#Vertical stack
#No.of columns should equal
np.vstack((arr1,arr2))

array([[6, 2, 3, 4, 6],
       [1, 1, 4, 2, 3],
       [3, 3, 6, 3, 3],
       [6, 4, 3, 2, 2],
       [6, 8, 3, 4, 6],
       [5, 4, 1, 3, 8],
       [4, 1, 3, 8, 5],
       [6, 2, 6, 3, 5]])

In [ ]:
#Question

marks = np.random.randint(0,100,50)
print(marks)

for i in range(len(marks)):
  if marks[i]>75:
    print('Marks : Distinction!')
  elif marks[i]>=60 and marks[i]<75:
    print('Marks : First division')
  elif marks[i]>=35 and marks[i]<60:
    print('Marks : Second division')
  else:
    print('Marks : Fail!')

[70 55 74 13 44 87 58 40 59 62 72 36 95 76 87 64 71 26 49 96 45 44  0 33
 34 50 41 12  4 63 41 22 92 80 10 52  2 65 23 81 81 89 59 66 84 60 93 25
 51  4]
Marks : First division
Marks : Second division
Marks : First division
Marks : Fail!
Marks : Second division
Marks : Distinction!
Marks : Second division
Marks : Second division
Marks : Second division
Marks : First division
Marks : First division
Marks : Second division
Marks : Distinction!
Marks : Distinction!
Marks : Distinction!
Marks : First division
Marks : First division
Marks : Fail!
Marks : Second division
Marks : Distinction!
Marks : Second division
Marks : Second division
Marks : Fail!
Marks : Fail!
Marks : Fail!
Marks : Second division
Marks : Second division
Marks : Fail!
Marks : Fail!
Marks : First division
Marks : Second division
Marks : Fail!
Marks : Distinction!
Marks : Distinction!
Marks : Fail!
Marks : Second division
Marks : Fail!
Marks : First division
Marks : Fail!
Marks : Distinction!
Marks : Distinction!
Marks :

* Matrix multiplication

In [ ]:
mat1 = np.random.randint(1,9,20).reshape(5,4)
mat2 = np.random.randint(1,9,12).reshape(4,3)
print(mat1)
print(mat2)

[[4 8 1 1]
 [4 5 7 8]
 [1 2 2 2]
 [2 2 1 2]
 [8 6 6 3]]
[[8 2 6]
 [2 3 5]
 [3 8 6]
 [4 2 2]]


In [ ]:
np.dot(mat1,mat2)

array([[ 55,  42,  72],
       [ 95,  95, 107],
       [ 26,  28,  32],
       [ 31,  22,  32],
       [106,  88, 120]])